package com.github.mangila.webshop.shared.identity.application;


import com.github.mangila.webshop.shared.Ensure;
import com.github.mangila.webshop.shared.identity.domain.Identity;
import com.github.mangila.webshop.shared.identity.domain.IdentityRepository;
import com.github.mangila.webshop.shared.identity.domain.cqrs.NewIdentityCommand;
import org.springframework.stereotype.Service;

import java.util.UUID;

@Service
public class IdentityService {

    private final IdentityRepository repository;

    public IdentityService(IdentityRepository repository) {
        this.repository = repository;
    }

    public Identity generate(NewIdentityCommand command) {
        Ensure.notNull(command, NewIdentityCommand.class);
        Identity identity = Identity.createNew(command.domain());
        return repository.save(identity);
    }

    public boolean hasGenerated(UUID id) {
        return repository.existsById(id);
    }

    public void ensureHasGenerated(UUID id) {
        Ensure.isTrue(hasGenerated(id), "%s has not been generated by identity service");
    }
}
