# Application Properties
app:
  product:
    scheduler:
      enabled: true
      delete-marked:
        fixed-rate: 5s
  outbox:
    scheduler:
      enabled: true
      delete-published:
        fixed-rate: 5s
      fill-queues:
        fixed-rate: 5s
    message-relay:
      enabled: true
      process-queue:
        fixed-rate: 500ms
      process-dlq:
        fixed-rate: 500ms
# Spring Properties
spring:
  application:
    name: "webshop"
  jpa:
    properties:
      hibernate.generate_statistics: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: "jdbc:postgresql://localhost:5432/webshop"
    username: "my_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: "webshop-hikari-pool"
      maximum-pool-size: 10
      minimum-idle: 5
  sql:
    init:
      mode: never
      platform: postgres
  graphql:
    graphiql:
      enabled: false
      path: "/graphiql"
    schema:
      file-extensions: ".graphql"
      inspection:
        enabled: true
  threads:
    virtual:
      enabled: true
  task:
    execution:
      mode: force
      thread-name-prefix: "spring-task-"
# Logging properties
logging:
  level:
    root: info
# SpringDoc
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
# Actuator
management:
  server:
    port: 8888
  tracing:
    sampling:
      probability: 1
    enabled: true
  endpoints:
    web:
      # Expose all endpoints for development purposes
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
    access:
      default: unrestricted
  zipkin:
    tracing:
      export:
        enabled: true
# Jdbc Observation
jdbc:
  datasource-proxy:
    type: concrete
    enabled: true