# Spring Properties
spring:
  jpa:
    properties:
      hibernate.generate_statistics: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      platform: postgres
  graphql:
    graphiql:
      enabled: true
# Logging properties
logging:
  level:
    root: info