# Spring Properties
spring:
  application:
    name: "webshop"
  datasource:
    username: "my_user"
    password: "secret"
    url: "jdbc:postgresql://localhost:5432/webshop"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  sql:
    init:
      mode: always
      platform: postgres
  graphql:
    graphiql:
      enabled: true
      path: "/graphiql"
    schema:
      file-extensions: ".graphql"
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: true
      skip:
        in-tests: true