package com.github.mangila.webshop.product.application.service;

import com.github.mangila.webshop.identity.application.IdentityService;
import com.github.mangila.webshop.product.application.ProductOutboxMapper;
import com.github.mangila.webshop.product.domain.Product;
import com.github.mangila.webshop.product.domain.ProductCommandRepository;
import com.github.mangila.webshop.product.domain.cqrs.ProductInsertCommand;
import com.github.mangila.webshop.product.domain.event.ProductEvent;
import com.github.mangila.webshop.product.domain.primitive.ProductId;
import com.github.mangila.webshop.shared.Ensure;
import com.github.mangila.webshop.shared.SpringEventPublisher;
import com.github.mangila.webshop.shared.exception.ResourceNotFoundException;
import com.github.mangila.webshop.shared.model.OutboxEvent;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ProductCommandService {

    private final ProductOutboxMapper outboxMapper;
    private final ProductCommandRepository repository;
    private final SpringEventPublisher publisher;
    private final IdentityService identityService;

    public ProductCommandService(ProductOutboxMapper outboxMapper,
                                 ProductCommandRepository repository,
                                 SpringEventPublisher publisher,
                                 IdentityService identityService) {
        this.outboxMapper = outboxMapper;
        this.repository = repository;
        this.publisher = publisher;
        this.identityService = identityService;
    }

    @Transactional
    public Product insert(ProductInsertCommand command) {
        Ensure.notNull(command, ProductInsertCommand.class);
        Ensure.isTrue(identityService.hasGenerated(command.id().value()), "Id must be generated by identity service before calling insert command: %s".formatted(command.id().value()));
        Product product = repository.insert(command);
        OutboxEvent outboxEvent = outboxMapper.toOutboxEvent(
                ProductEvent.PRODUCT_CREATED,
                product);
        publisher.publishOutboxEvent(outboxEvent);
        return product;
    }

    @Transactional
    public void deleteByIdOrThrow(ProductId productId) {
        Ensure.notNull(productId, ProductId.class);
        Product product = repository.deleteById(productId).orElseThrow(() -> new ResourceNotFoundException(
                Product.class,
                productId
        ));
        OutboxEvent outboxEvent = outboxMapper.toOutboxEvent(
                ProductEvent.PRODUCT_DELETED,
                product);
        publisher.publishOutboxEvent(outboxEvent);
    }
}
