services:
  zipkin:
    image: 'openzipkin/zipkin:latest'
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - 'STORAGE_TYPE=mem'
  postgres:
    image: 'postgres:17.5-alpine'
    environment:
      - 'POSTGRES_DB=webshop'
      - 'POSTGRES_USER=my_user'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'