# Spring Properties
spring:
  boot:
    admin:
      client:
        url: "http://localhost:8081"
        enabled: true
  application:
    name: "webshop"
  jpa:
    properties:
      hibernate.generate_statistics: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: "my_user"
    password: "secret"
    url: "jdbc:postgresql://localhost:5432/webshop"
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: "webshop-hikari-pool"
      maximum-pool-size: 10
      minimum-idle: 5
  sql:
    init:
      mode: always
      platform: postgres
  graphql:
    graphiql:
      enabled: true
      path: "/graphiql"
    schema:
      file-extensions: ".graphql"
  threads:
    virtual:
      enabled: true
  task:
    execution:
      mode: force
      thread-name-prefix: "spring-task-"
  docker:
    compose:
      enabled: true
      skip:
        in-tests: true
      file: "./backend/compose.yaml"
# Logging properties
logging:
  file:
    name: "webshop.log"
  level:
    web: debug
    sql: debug
# SpringDoc
springdoc:
  show-actuator: true
# Actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted