package com.github.mangila.webshop.identity.application;

import com.github.mangila.webshop.identity.domain.cqrs.NewDomainIdCommand;
import com.github.mangila.webshop.shared.Ensure;
import jakarta.validation.Valid;
import org.springframework.stereotype.Service;
import org.springframework.validation.annotation.Validated;

import java.util.UUID;

@Service
@Validated
public class DomainIdFacade {

    private final DomainIdService service;
    private final DomainIdMapper mapper;

    public DomainIdFacade(DomainIdService service,
                          DomainIdMapper mapper) {
        this.service = service;
        this.mapper = mapper;
    }

    public UUID generate(@Valid NewDomainIdRequest request) {
        NewDomainIdCommand command = mapper.toCommand(request);
        return service.generate(command).id();
    }

    public void ensureHasGenerated(UUID id) {
        Ensure.isTrue(service.hasGenerated(id), "Domain id must be generated by the identity service");
    }
}
